batch_size: 16
d_model: 256
dataset:
  data_dir: palestrina/data/palestrina_csv_mid
  seq_len_chord: 88
  seq_len_note: 246
device: mps
epochs: 80
experiment: bidirectional_RIPO
lr: 0.001
optimizer: adam
relative_pitch_attention:
  attention_conf:
    attention_type: rgl_rel_pitch_dur
    if_add_relative_duration: true
    if_add_relative_idx: true
    if_add_relative_idx_no_mask: false
    if_add_relative_pitch: true
  d_model: 256
  device: mps
  dim_feedforward: 2048
  dropout: 0.2
  dur_dim: 17
  dur_embedding_conf:
    base: 7920
    d_model: 256
    device: mps
    emb_nn: true
    if_trainable: true
    translation_bias_type: nd
    type: se
  emb_size: 128
  nhead: 8
  nlayers: 2
  pitch_dim: 128
  pitch_embedding_conf:
    base: 9919
    d_model: 256
    device: mps
    emb_nn: true
    if_trainable: true
    translation_bias_type: nd
    type: se
  position_encoding_conf:
    device: mps
    if_global_timing: true
    if_index: true
    if_modulo_timing: true
